# -*- coding: utf-8 -*-
"""project1(smartshop calculator).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iXG7axc0E5XOd3LMVTCIY8hBBq6-Si-9

**Style Zone**

| **Item**    | **Price** (Rs) |
| ------- | ---------- |
| T-Shirt | 800        |
| Jeans   | 1500       |
| Shirt   | 1200       |
| Dress   | 2000       |
| Shoes   | 3000       |
"""

shop_name = "Style Zone"
items = ["T-Shirt", "Jeans", "Shirt", "Dress", "Shoes"]
prices = [800, 1500, 1200, 2000, 3000]

print("Welcome to", shop_name)


for i in range(len(items)):
    print(i+1, ".", items[i], "-", prices[i], "Rs")


choice = int(input("Enter your choice (1-5): "))
quantity = int(input("Enter quantity: "))


price = float(prices[choice - 1])

total = price * quantity

student_input = input("Are you a student? (yes/no): ")


student = student_input.lower() == "yes"


if student:
    discount = total * 0.10
    total = total - discount
    print("10% Student Discount Applied!")
else:
    print("No Discount Applied!")


print("\n BILL DETAILS ")
print("Item Selected:", items[choice - 1])
print("Quantity:", quantity)
print("Total Amount:", total, "Rs")

coupon_code = input("Enter coupon code (SAVE10 / FLAT200 / NONE): ")

if coupon_code.upper() == "SAVE10":
    total = total - (total * 0.10)
    print("Coupon SAVE10 Applied (10% Off)")
elif coupon_code.upper() == "FLAT200":
    total = total - 200
    print("Coupon FLAT200 Applied (200 Rs Off)")
elif coupon_code.upper() == "NONE":
    print("No Coupon Applied")
else:
    print("Invalid Coupon Code")